### ISSUE TITLE
Direct access to path

### ISSUE THREAD

**Issue by bedros-p** [Slyplayer8990/cloudy#6]
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/k3s.py#L49-L63 
Specifically line 63 - a user can just place `../` in the name to go back one folder - this is not good, name can be `../existingname` allowing for overwriting different machines

https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/k3s.py#L143-L144 same here

**Comment by Slyplayer8990** [comment]
Any suggestions for fixing it?

**Comment by Slyplayer8990** [comment]
I will use database for it... Thank for reporting.

**Comment by Slyplayer8990** [comment]
`nodelocation = "/var/lib/cloudy/machines/ubuntu-k3c.raw"
    os.rename(nodelocation, node_name + ".raw")
    shutil.copyfile(image, nodelocation)`

**Comment by Slyplayer8990** [comment]
Thanks....
