### ISSUE TITLE
Direct concat of string allows for malformed xml 

### ISSUE THREAD

**Issue by bedros-p** [Slyplayer8990/cloudy#7]
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/k3s.py#L66-L109

https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/k3s.py#L145-L187
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/machines.py#L54-L99

can crash the whole service
also worth noting that a user can overwrite the rest of the xml by writing their own xml inside the variables concatenated through

**Comment by Slyplayer8990** [comment]
Any suggestions for creating that xml's in a different way?
