### ISSUE TITLE
hardcoded database connections

### ISSUE THREAD

**Issue by bedros-p** [Slyplayer8990/cloudy#8]
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/k3s.py#L6
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/modules/machines.py#L10
https://github.com/Slyplayer8990/cloudy/blob/3289fbd1e618223e23011e3c78061933e2dafb5d/web/page/secure.php#L1-L8

**Comment by Slyplayer8990** [comment]
I will use dotenv for it. Thanks...

**Comment by Slyplayer8990** [comment]
No need to fix it now, i can fix it later....

**Comment by bedros-p** [comment]
whats with the `not planned`? Hardcoding it in every single file would mean if someone wants to change the default creds, they'd have to go across the whole thing 

unchangeable default creds remove meaning from a login system overall
